// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Voitures.Shared.Data;

#nullable disable

namespace Voitures.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Voitures.Entity.Entretien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescritionEntretien")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VoitureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VoitureId");

                    b.ToTable("Entretiens");
                });

            modelBuilder.Entity("Voitures.Entity.Voiture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Energie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Immatriculation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marque")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modele")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Voitures");
                });

            modelBuilder.Entity("Voitures.Entity.Entretien", b =>
                {
                    b.HasOne("Voitures.Entity.Voiture", null)
                        .WithMany("Entretiens")
                        .HasForeignKey("VoitureId");
                });

            modelBuilder.Entity("Voitures.Entity.Voiture", b =>
                {
                    b.Navigation("Entretiens");
                });
#pragma warning restore 612, 618
        }
    }
}
